# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.com for more information
default_language_version:
  # default language version for each language used in the repository
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: trailing-whitespace
  - repo: https://github.com/arslantoor/django-precomit.git/
    rev: v2.2.0
    hooks:
      - id: check-ast
